### ISSUE TITLE
AndroidManifest.xml

### ISSUE THREAD

**Issue by irfanalibutt** [jgao1/Restaurant-Finder#1]
Hi,
Please add manifest file into your project. thanks
I am getting following error :
> File 'C:\Users\IrfanAndroidStudioProjects\Restaurant-Finder-master\app\src\main\AndroidManifest.xml' specified for property 'manifest' does not exist.

**Comment by jgao1** [comment]
Thanks for your interest in this repo! I didn't include it because it contained the Google API key. Now it's back and you need to fill it with your own key.
